version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: kgas-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - /home/brian/Digimons/examples/../src/monitoring/dashboards:/etc/grafana/provisioning/dashboards/kgas:ro
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    networks:
      - kgas-monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: kgas-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - kgas-monitoring

volumes:
  grafana-data:
  prometheus-data:

networks:
  kgas-monitoring:
    driver: bridge