version: "3.9"

services:
  neo4j:
    image: neo4j:5.13.0-community
    container_name: digimons-neo4j-test
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_test_data:/data
      - neo4j_test_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2.4-alpine
    container_name: digimons-redis-test
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  neo4j_test_data:
  neo4j_test_logs: 