apiVersion: v1
kind: ConfigMap
metadata:
  name: kgas-config
  labels:
    app: kgas-api
data:
  NEO4J_URI: "bolt://neo4j-service:7687"
  REDIS_URL: "redis://redis-service:6379"
  PROMETHEUS_METRICS_PORT: "9090"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'kgas-api'
      static_configs:
      - targets: ['kgas-api-service:8000']