apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgas-api
  labels:
    app: kgas-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kgas-api
  template:
    metadata:
      labels:
        app: kgas-api
    spec:
      containers:
      - name: kgas-api
        image: kgas:latest
        ports:
        - containerPort: 8000
        env:
        - name: NEO4J_URI
          value: "bolt://neo4j-service:7687"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5