apiVersion: v1
kind: Secret
metadata:
  name: kgas-secrets
  labels:
    app: kgas-api
type: Opaque
data:
  # These are base64 encoded values - replace with actual encoded secrets
  SECRET_KEY: c2VjcmV0X2tleV9jaGFuZ2VfbWU=  # secret_key_change_me
  API_KEY: YXBpX2tleV9jaGFuZ2VfbWU=        # api_key_change_me
  NEO4J_PASSWORD: cHJvZHVjdGlvbl9wYXNzd29yZA== # production_password
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  labels:
    app: grafana
type: Opaque
data:
  # base64 encoded: production_password
  GF_SECURITY_ADMIN_PASSWORD: cHJvZHVjdGlvbl9wYXNzd29yZA==