apiVersion: v1
kind: Service
metadata:
  name: kgas-api-service
  labels:
    app: kgas-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: kgas-api
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  labels:
    app: neo4j
spec:
  ports:
  - port: 7687
    targetPort: 7687
    protocol: TCP
    name: bolt
  - port: 7474
    targetPort: 7474
    protocol: TCP
    name: http
  selector:
    app: neo4j
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis