api:
  anthropic_api_key: ''
  google_api_key: ''
  max_retries: 3
  openai_api_key: ''
  timeout: 30
database:
  database: neo4j
  host: localhost
  password: 'testpassword'
  port: 7687
  username: neo4j
system:
  backup_enabled: true
  encryption_enabled: true
  log_level: INFO
  max_workers: 4
  metrics_enabled: true
