name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.7-dind
        privileged: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Start test stack
        run: |
          docker compose -f docker-compose.test.yml up -d

      - name: Wait for services to be healthy
        run: |
          # Wait up to 2 minutes for healthchecks
          timeout=120
          interval=5
          elapsed=0
          until docker inspect --format='{{json .State.Health.Status}}' digimons-neo4j-test | grep -q "healthy"; do
            sleep $interval
            elapsed=$(( elapsed + interval ))
            if [ $elapsed -ge $timeout ]; then
              echo "❌ Services did not become healthy in time" >&2
              docker compose -f docker-compose.test.yml logs
              exit 1
            fi
          done

      - name: Run tests with tox
        env:
          KGAS_PII_PASSWORD: test-password
          KGAS_PII_SALT: test-salt
        run: |
          tox

      - name: Shut down stack
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v 