name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  verification-matrix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_llm.txt
        pip install pytest pytest-cov

    - name: Parse verification commands
      id: parse
      run: |
        python scripts/parse_verification_commands.py > commands.txt

    - name: Run verification commands matrix
      run: |
        set -e
        while IFS= read -r cmd; do
          echo "Running: $cmd"
          eval "$cmd"
        done < commands.txt

  integration-full:
    runs-on: ubuntu-latest
    needs: verification-matrix
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_llm.txt
        pip install pytest pytest-cov
    
    - name: Start Neo4j
      run: |
        docker-compose up -d neo4j
        sleep 30  # Wait for Neo4j to start
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --cov=src --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  doc-governance:
    runs-on: ubuntu-latest
    needs: verification-matrix
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify documentation claims
      run: |
        chmod +x scripts/verify_all_documentation_claims.sh
        ./scripts/verify_all_documentation_claims.sh
    
    - name: Check documentation drift
      run: |
        chmod +x scripts/check_doc_drift.py
        python scripts/check_doc_drift.py 